# Generated by Django 3.1.7 on 2021-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='climbs.challenge'),
        ),
    ]
